Добавит аутентификацию
htmlacademy-react/506463-six-cities-6 pull request #12
Opened 2021-03-04 18:22 UTC by levallevchenko

2021-03-05 09:44 UTC, balesniy commented on src/components/private-route/private-route.jsx
> +    if (!isOffersLoaded) {
нам нужно проверить ответ сервера на запрос авторизации

2021-03-05 15:14 UTC, balesniy requested changes

2021-03-05 15:14 UTC, balesniy commented on src/components/not-found/not-found.jsx
> +import {Header} from '../header/header';
импорт компонента без коннекта

2021-03-05 15:14 UTC, balesniy commented on src/store/api-actions.js
> +    .catch(() => {})
сервер может ответить ошибкой, и тогда нам нужно показать сообщение пользователю,

2021-03-05 15:14 UTC, balesniy commented on src/components/private-route/private-route.jsx
> +    if (!isOffersLoaded) {
загрузка данных не говорит об авторизации пользователя

2021-03-06 14:50 UTC, levallevchenko commented on src/components/not-found/not-found.jsx
> +import {Header} from '../header/header';
Исправила

2021-03-06 14:51 UTC, levallevchenko commented on src/store/api-actions.js
> +    .catch(() => {})
Да, на лекции сказали, что пока можно так оставить, видимо потом дорабатывать будем

2021-03-06 14:57 UTC, levallevchenko commented on src/components/private-route/private-route.jsx
> +    if (!isOffersLoaded) {
Попыталась сделать проверку добавив checkAuth в PrivateRoute, как-то так:
<img width="385" alt="Снимок экрана 2021-03-06 в 16 27 19" src="https://user-images.githubusercontent.com/36822971/110210955-5ecb0880-7ea5-11eb-9813-2075bc45e106.png">

Но не вышло, в итоге добавила проверку авторизации в индексе при загрузке всего приложения — https://github.com/htmlacademy-react/506463-six-cities-6/pull/12/commits/be194cdc21dd8b7c3d3974c3661e1283fef8523f#diff-bfe9874d239014961b1ae4e89875a6155667db834a410aaaa2ebe3cf89820556

2021-03-06 14:59 UTC, levallevchenko commented on src/components/private-route/private-route.jsx
> +    if (!isOffersLoaded) {
Ещё добавила history для редиректа с экрана Sign-in на главную

2021-03-07 12:56 UTC, balesniy approved these changes

2021-03-07 12:56 UTC, balesniy commented on src/components/app/app.jsx
> +  offers: PropTypes.arrayOf(offerPropTypes),
не забывай про isRequired

2021-03-07 12:56 UTC, balesniy commented on src/index.js
> +store.dispatch(checkAuth()).then(() => {
на время ожидания ответа сервер пользователю нужно показать лоадер

2021-03-07 12:56 UTC, balesniy commented on src/index.js
> +          offers = {offers} reviews = {reviews} nearbyOffersArray = {nearbyOffersArray}
моковые данные уже можно отключить

2021-03-07 12:56 UTC, balesniy commented on src/components/city-list/city-list.jsx
> +      {Object.values(CityName).map((city, id) => (<li className="locations__item" key={city + id}>
в CityName оформлен массив, Object.values лишний

2021-03-07 12:56 UTC, balesniy commented on src/mocks/data.js
> +export const CityName = [
Б10. Массивы названы существительными во множественном числе
Б5. Название переменных, параметров, свойств и методов начинается со строчной буквы

2021-03-07 12:56 UTC, merged

2021-03-07 22:03 UTC, levallevchenko commented on src/index.js
> +          offers = {offers} reviews = {reviews} nearbyOffersArray = {nearbyOffersArray}
Пока оставила только для пропсов Room, страницу предложения буду в следующем задании доделывать

2021-03-07 22:05 UTC, levallevchenko commented on src/components/city-list/city-list.jsx
> +      {Object.values(CityName).map((city, id) => (<li className="locations__item" key={city + id}>
Был оформлен перечислением, поправила

2021-03-07 22:09 UTC, levallevchenko commented on src/mocks/data.js
> +export const CityName = [
Это у меня перечисление :) [Критерий Б9](https://up.htmlacademy.ru/react/6/criteries#b9)

2021-03-07 22:16 UTC, levallevchenko commented on src/components/app/app.jsx
> +  offers: PropTypes.arrayOf(offerPropTypes),
fe7d63a

2021-03-07 22:53 UTC, levallevchenko commented on src/index.js
> +store.dispatch(checkAuth()).then(() => {
Что-то запуталась и не поняла, как это корректно сделать, не усложнив. Нужно в стейте создать ключ isAuthInfoLoaded и как-то в индексе прямо его проверять?

2021-03-08 08:03 UTC, balesniy commented on src/index.js
> +store.dispatch(checkAuth()).then(() => {
да, с ключом хорошая идея, но в индексе его проверять не надо, нам нужен компонент, можно в App