Добавит загрузку предложения и отправку комментариев
htmlacademy-react/506463-six-cities-6 pull request #14
Opened 2021-03-13 17:22 UTC by levallevchenko

2021-03-14 12:02 UTC, balesniy requested changes

2021-03-14 12:02 UTC, balesniy commented on src/components/app/app.jsx
> +  // Сначала этот вариант сработал, теперь бесконечная загрузка
у меня dispatch((checkAuth())) бросает 401 ошибку, которая не ставит флаг isAuthInfoLoaded, REQUIRED_AUTHORIZATION меняет только authStatus

2021-03-16 08:26 UTC, levallevchenko commented on src/components/review-form/review-form.jsx
> +    setUserForm({...userForm, ...initialState});
e16d17c

2021-03-16 16:36 UTC, levallevchenko commented on src/components/review-form/review-form.jsx
> +    setUserForm({...userForm, ...initialState});
b418f32

2021-03-19 08:45 UTC, balesniy approved these changes

2021-03-19 08:45 UTC, balesniy commented on src/components/review-form/review-form.jsx
> +      <textarea onChange={handleFieldChange} className="reviews__textarea form__textarea" id="review" name="review" placeholder="Tell how was your stay, what you like and what can be improved" value=
disabled={isCommentLoading}

2021-03-19 08:45 UTC, merged

2021-03-19 09:16 UTC, levallevchenko commented on src/components/review-form/review-form.jsx
> +      <textarea onChange={handleFieldChange} className="reviews__textarea form__textarea" id="review" name="review" placeholder="Tell how was your stay, what you like and what can be improved" value=
Да, точно, пропустила :)