Добавит состояние
htmlacademy-react/506463-six-cities-6 pull request #6
Opened 2021-02-15 19:34 UTC by levallevchenko

2021-02-15 20:51 UTC, balesniy requested changes
обрати внимание на генерацию id для ключей, я не стал во всех списках указывать, ключ должен быть не только уникальным, но и повторяемым, случайные сломают оптимизацию

2021-02-15 20:51 UTC, balesniy commented on src/components/app/app.jsx
> +          <Room offers = {offers} reviews = {reviews} />
для компонента предложения имеет смысл передавать именно его данные, а не весь список offers, и отдельно он ждет список "предложения неподалеку"

2021-02-15 20:51 UTC, balesniy commented on src/components/favorites-item/favorites-item.jsx
> +        <React.Fragment>
фрагмент тут лишний, у списка есть общий div

2021-02-15 20:51 UTC, balesniy commented on src/components/favorites-item/favorites-item.jsx
> +          {offers.map((offer) => <Offer key={nanoid()} offer={offer} CardType={CardType} />)}
nanoid вернет новый ключ при каждом рендере, и оптимизации сломаются, нам нужно дать объекту id на этапе подготовки моков, и тут его использовать уже готовый

2021-02-15 20:51 UTC, balesniy commented on src/components/favorites/favorites.jsx
> +  const favoriteOffers = offers.filter((offer) => offer.isFavorite);
оптимальнее фильтровать данные "снаружи" компонента, и передавать в него уже готовый список. этот код будет выполнятся при каждом рендере

2021-02-15 20:51 UTC, balesniy commented on src/components/offer-list/offer-list.jsx
> +const OfferList = (props) => {
В стейте компонента должна быть активная карточка с предложением

2021-02-15 20:51 UTC, balesniy commented on src/components/offer/offer.jsx
>            </div>
обрати внимание на звездочки, они должны соответствовать рейтингу

2021-02-15 20:51 UTC, balesniy commented on src/components/review-form/review-form.jsx
> +        <input onChange={handleReviewChange} className="form__rating-input visually-hidden" name="rating" defaultValue={5} id="5-stars" type="radio" />
список инпутов имеет смысл оформить в цикле

2021-02-15 20:51 UTC, balesniy commented on src/components/review-form/review-form.jsx
> +      <textarea onChange={handleFieldChange} className="reviews__textarea form__textarea" id="review" name="review" placeholder="Tell how was your stay, what you like and what can be improved" defaul
defaultValue используется для установки начального состояния, для управляемого компонента нужен value

2021-02-15 20:51 UTC, balesniy commented on src/components/review-form/review-form.jsx
> +        <input onChange={handleReviewChange} className="form__rating-input visually-hidden" name="rating" defaultValue={1} id="1-star" type="radio" />
для связи инпутов в форме с состоянием нужно установить атрибут checked

2021-02-15 20:51 UTC, balesniy commented on src/components/room/room.jsx
> +  const id = window.location.pathname.slice(-1);
для отладки хорошее решение, не забудь потом его убрать, у нас по критериям разрешен только react-router

2021-02-15 20:51 UTC, balesniy commented on src/components/room/room.jsx
>            </div>
картинки тоже можно из моков заполнить

2021-02-15 20:51 UTC, balesniy commented on src/components/room/room.jsx
> +import Form from '../review-form/review-form';
компоненту лучше дать более наглядное имя, Form слишком общее

2021-02-15 20:51 UTC, balesniy commented on src/components/room/room.jsx
>            </div>
near-places уже тоже можно из пропс заполнять

2021-02-15 20:51 UTC, balesniy commented on src/mocks/reviews.js
> +    reviews.push(review);
у нас отзывы будут приходить с сервера отдельным списком по id отеля, сейчас для отладки можно их сгруппировать при генерации, чтобы привязаться к отелю

2021-02-15 20:51 UTC, balesniy commented on src/prop-types/offer.js
> +    hotelImages: PropTypes.string.isRequired,
тут будет массив картинок

2021-02-16 14:40 UTC, levallevchenko commented on src/components/favorites-item/favorites-item.jsx
> +          {offers.map((offer) => <Offer key={nanoid()} offer={offer} CardType={CardType} />)}
7d242d4

2021-02-16 15:16 UTC, levallevchenko commented on src/components/favorites/favorites.jsx
> +  const favoriteOffers = offers.filter((offer) => offer.isFavorite);
d6730a8

2021-02-16 17:43 UTC, levallevchenko commented on src/components/app/app.jsx
> +          <Room offers = {offers} reviews = {reviews} />
d6730a8

2021-02-16 17:44 UTC, levallevchenko commented on src/components/room/room.jsx
>            </div>
d6730a8

2021-02-16 21:04 UTC, levallevchenko commented on src/components/room/room.jsx
>            </div>
dcafd25

2021-02-16 21:04 UTC, levallevchenko commented on src/components/app/app.jsx
> +          <Room offers = {offers} reviews = {reviews} />
dcafd25

2021-02-16 21:52 UTC, levallevchenko commented on src/mocks/reviews.js
> +    reviews.push(review);
22f4828

2021-02-17 07:35 UTC, levallevchenko commented on src/components/offer-list/offer-list.jsx
> +const OfferList = (props) => {
d28f9c2

2021-02-17 10:27 UTC, levallevchenko commented on src/components/review-form/review-form.jsx
> +      <textarea onChange={handleFieldChange} className="reviews__textarea form__textarea" id="review" name="review" placeholder="Tell how was your stay, what you like and what can be improved" defaul
d28f9c2

2021-02-17 10:28 UTC, levallevchenko commented on src/components/review-form/review-form.jsx
> +        <input onChange={handleReviewChange} className="form__rating-input visually-hidden" name="rating" defaultValue={5} id="5-stars" type="radio" />
d28f9c2

2021-02-17 10:28 UTC, levallevchenko commented on src/components/review-form/review-form.jsx
> +        <input onChange={handleReviewChange} className="form__rating-input visually-hidden" name="rating" defaultValue={1} id="1-star" type="radio" />
А у меня же он как раз в обработчике устанавливается? Или ты не это имеешь в виду?

2021-02-17 10:53 UTC, balesniy commented on src/components/review-form/review-form.jsx
> +        <input onChange={handleReviewChange} className="form__rating-input visually-hidden" name="rating" defaultValue={1} id="1-star" type="radio" />
самому элементу нужно как то узнать, выбран он или нет, для этого нужно атрибут checked привязать к состоянию, то есть отмечать тот, который выбрал пользователь

2021-02-17 15:01 UTC, balesniy requested changes

2021-02-17 15:01 UTC, balesniy commented on src/prop-types/offer.js
> +  offers: PropTypes.arrayOf(PropTypes.objectOf(PropTypes.shape({
https://stackoverflow.com/questions/45764746/react-proptypes-objectof-vs-shape - PropTypes.objectOf нужен для описания типов значений, а shape для описания формы по ключам

2021-02-17 16:20 UTC, levallevchenko commented on src/components/review-form/review-star/review-star.jsx
> +      <label htmlFor={id} className="reviews__rating-label form__rating-label" title="perfect">
Done

2021-02-17 16:20 UTC, levallevchenko commented on src/components/review-form/review-form.jsx
> +      <textarea onChange={handleFieldChange} className="reviews__textarea form__textarea" id="review" name="review" placeholder="Tell how was your stay, what you like and what can be improved" defaul
Здесь пропустила просто

2021-02-17 16:53 UTC, levallevchenko commented on src/mocks/offers.js
> +  offers.map((offer) => {
Почему не используется? Я его вот сюда записала:
```
const generateNearbyOffers = (offers) => {
  const nearbyOffersArray = [];
  offers.map((offer) => {
    const nearbyOffers = generateRandomArray(offers, minCountData.NEARBY_PLACES_COUNT, maxCountData.NEARBY_PLACES_COUNT);
    const uniqueNearbyOffers = getUniqueArray(nearbyOffers);

    nearbyOffersArray.push(uniqueNearbyOffers);
    **offer.uniqueNearbyOffers = uniqueNearbyOffers;**
  });
```
   но в целом может оно там и не пригодится

2021-02-17 17:05 UTC, levallevchenko commented on src/prop-types/offer.js
> +  offers: PropTypes.arrayOf(PropTypes.objectOf(PropTypes.shape({
👍 поняла

2021-02-17 17:13 UTC, levallevchenko commented on src/components/review-form/review-form.jsx
>      const {name, value} = evt.target;
Изначально делала по [этой демке](https://up.htmlacademy.ru/react/6/demos/4849#1). Про value отдельно в компоненте почему-то там ничего нет. Хотя, конечно, он нужен. Запутал defaultValue. 

Думала, что если переключать checked в обработчике, то компонент об этом будет знать, в разметке изменялся атрибут. Сделала теперь как-то так, но кажется, что тоже не то

2021-02-17 18:35 UTC, balesniy commented on src/components/review-form/review-form.jsx
>      const {name, value} = evt.target;
угу, спасибо за демку, теперь понятно откуда. без явной установки значения получается неуправляемый компонент, который хранит состояние в разметке.

2021-02-17 18:37 UTC, balesniy commented on src/components/review-form/review-form.jsx
> +        {starIds.map((id) => <ReviewStar key={id} id = {id} onInputChange = {handleInputChange} rating = {id + 1} title = {starsDescriptionArray[id]} checked = {rating === id + 1} />)}
👍

2021-02-17 18:40 UTC, balesniy commented on src/prop-types/offer.js
> +    city: PropTypes.objectOf(PropTypes.shape({
пересмотри все типы, паттерн `PropTypes.objectOf(PropTypes.shape` скорее всего не нужен

2021-02-17 19:09 UTC, balesniy approved these changes
c PropTypes.objectOf и PropTypes.shape осталось разобраться, с управляемыми компонентами все отлично получилось 👍

2021-02-17 19:12 UTC, balesniy commented on src/mocks/offers.js
> +  offers.map((offer) => {
offers.map вернет массив из undefined, он нам точно не нужен, тут или forEach вместо map который на результат вызова колбэка не смотрит, или тогда  return offers.map... и в колбэке return uniqueNearbyOffers вместо push

2021-02-17 19:13 UTC, merged

2021-02-17 20:14 UTC, levallevchenko commented on src/components/review-form/review-form.jsx
>      const {name, value} = evt.target;
@balesniy так получается в демке ошибка? Или я просто не до конца поняла?

2021-02-17 20:35 UTC, balesniy commented on src/components/review-form/review-form.jsx
>      const {name, value} = evt.target;
да, демка недоработана, управляемость обеспечивается установкой value на поле, тогда пользователь не сможет его изменить

2021-02-18 08:39 UTC, levallevchenko commented on src/prop-types/offer.js
> +    city: PropTypes.objectOf(PropTypes.shape({
ОЙ, это я поторопилась, не заметила, что везде так понаписала

2021-02-18 08:40 UTC, levallevchenko commented on src/components/review-form/review-form.jsx
>      const {name, value} = evt.target;
Ок, передам тогда авторам